### ISSUE TITLE
[Feature Request] UUID support as an arg

### ISSUE THREAD

**Issue by KMilhan** [temporalio/sdk-python#113]
### Is your feature request related to a problem? Please describe.

I tried to use UUID as an argument of activity. Received an error that UUID is not JSON serializable.

### Describe the solution you'd like

UUID is considered JSON serializable in many popular Python libraries, for example, Pydantic and FastAPI, hence Python devs tend to consider UUID as JSON serializable objects. i.e., string form of UUID.

Is there any limitation from the Temporal core side? If not, it would be great to have UUID support in Python SDK.

**Comment by cretz** [comment]
I think FastAPI just uses Pydantic, so not sure it's "many" popular libs.

Yes, Pydantic probably considers several things JSON serializable that the Python JSON lib does not and we do not. I don't think any of our SDKs support serialization of UUIDs by default (except maybe Go because it's a byte array) and I'm not sure we want to make Python special here.

Pydantic also supports JSON serialization of dates/times, IP addresses, enums besides just `IntEnum`, `Path`s, etc. But we do not. We have to concern ourselves with cross-language compatibility. I will consult with the team, but i am not sure we should support these types by default in Python unless we support them by default in all of our SDKs.

**Comment by KMilhan** [comment]
Thank you very much for your thoughtful message.

Totally understand supporting various data types such as DateTime/path in a cross-platform/language environment is a challenge and appreciate all the consideration.

If you allow me to add a little bit more about UUID - it has quite a straightforward conversion (str to native ds) in popular languages, and it is a greatly common choice for unique ID design. For example, we use UUID for workflow ID where we want every workflow to be unique and don't want to limit the execution by it. I carefully believe that many other users have chosen a similar approach.

Thanks again for your consideration.

**Comment by cretz** [comment]
Definitely a straightforward conversion. As it is for many of those other types I listed. I am not sure UUID is special here nor am I sure that we need every SDK to support UUID as a type natively. I will consult with the team.

Of course, since the conversion is so straightforward you can do this conversion yourself and just store as a string. Just like you would a file path, IP address, or any other type with a string representation that Python doesn't consider JSON serializable.

**Comment by cretz** [comment]
I think we can reopen this until I at least get team confirmation that we do or don't want to support this.

**Comment by cretz** [comment]
After some research, yeah since UUIDs don't have nested abilities to auto-encode to JSON, it causes trouble with https://docs.python.org/3/library/dataclasses.html#dataclasses.asdict and similar use cases. So while we could support encoding single UUIDs to JSON and we could support decoding single UUIDs _and_ nested UUIDs from JSON, we cannot (easily) support encoding nested UUIDs to JSON.

Gonna close this for now as not supported, but if it's a large enough burden to rework our nested encoding, we can look into it.
