### ISSUE TITLE
[Bug] Cancelled workflow returns WorkflowExecutionStatus.FAILED status in workflow description

### ISSUE THREAD

**Issue by lambyqq** [temporalio/sdk-python#145]
### What are you really trying to do?

Cancel a running workflow and check the status in `wf_handle.describe().status`

### Describe the bug

Expect the status to be `WorkflowExecutionStatus.CANCELED`, but got `WorkflowExecutionStatus.FAILED`

### Minimal Reproduction

cancel a workflow and get its status

### Environment/Versions

- Temporal Version: [e.g. 1.14.0?] and/or SDK version
python-SDK: temporalio==0.1b1

### Additional context

I have to use a workaround to tell if workflow is cancelled:
```
wf_description.status == WorkflowExecutionStatus.FAILED
            and isinstance(wf_error.cause, CancelledError)
```

**Comment by cretz** [comment]
Thanks, I have confirmed at https://github.com/temporalio/sdk-python/blob/49ccd563c1120425fc78b792c7c9e02bf3670f1c/temporalio/worker/workflow_instance.py#L1229-L1236 we are not doing the right thing. We will solve this shortly.

Note to self/implementer:

* Change `cancel_workflow_execution` instead of `fail_workflow_execution` and confirm in tests
* Confirm in tests what happens if a cancellation error is raised outside of a cancellation request
