### ISSUE TITLE
[Feature Request] Reset Workflow

### ISSUE THREAD

**Issue by bbkgh** [temporalio/sdk-python#262]
Hi. Is there any way/code snippet to reset workflows in python sdk?

like this question
[https://community.temporal.io/t/how-do-i-restart-an-opened-workflow/1044/2](https://community.temporal.io/t/how-do-i-restart-an-opened-workflow/1044/2)

https://docs.temporal.io/tctl-v1/workflow#reset

**Comment by cretz** [comment]
There is not in any of our SDKs because this is an advanced concept. If you don't want to use the CLI, _technically_ you can call `await my_client.workflow_service.reset_workflow_execution(temporalio.api.workflowservice.v1.ResetWorkflowExecutionRequest(...` which would be calling the [raw API](https://github.com/temporalio/api/blob/386b7cf9dccba864bdb38f28699f216a0f3fb2ca/temporal/api/workflowservice/v1/service.proto#L246-L251) with a [raw API request](https://github.com/temporalio/api/blob/386b7cf9dccba864bdb38f28699f216a0f3fb2ca/temporal/api/workflowservice/v1/request_response.proto#L621-L632). But that is a bit of an advanced API.

Resets are meant to be rarely used, not necessarily part of normal code, so we may not provide a common code sample for this.

**Comment by cretz** [comment]
Closing as answered

**Comment by bbkgh** [comment]
Thanks for your help. I found that there is a "reset_type" in tctl (that can be LastContinuedAsNew) but it's not supported in ResetWorkflowExecutionRequest structure. what is reason of this mismatch? (background conversion in tctl or a missing field in proto or ...)

**Comment by cretz** [comment]
That is used to crawl the history to find a finishing task ID to reset to. See https://github.com/temporalio/tctl/blob/d124bd56ba6bce7d6b6b90decb5093d4c007c653/cli_curr/workflowCommands.go#L1438-L1490 and https://github.com/temporalio/tctl/blob/d124bd56ba6bce7d6b6b90decb5093d4c007c653/cli_curr/workflowCommands.go#L1796-L1824 and associated code.
