### ISSUE TITLE
[Feature Request] Support constructing JSONProtoPayloadConverter with google.protobuf.json_format.Parse options

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-python#315]
### Describe the solution you'd like

People may want to ignore unknown fields and right now they have to remake the class themselves. Make it easier to set the parse options if they wanted to construct this converter w/ different options. Can accept all options or at least ignore unknown fields.

**Comment by elliot-graebert-skydio** [comment]
This would be hugely helpful. Right now we are heading down the path of doing a custom payload converter because we can't just directly set the option for ignore unknown fields.

Really, what we want is compatibility with the https://pkg.go.dev/go.temporal.io/sdk/converter#ProtoJSONPayloadConverterOptions options.
