### ISSUE TITLE
[Feature Request] Implement `is_running` for `_WorkflowInstanceImpl`

### ISSUE THREAD

**Issue by tomasfarias** [temporalio/sdk-python#426]
### Is your feature request related to a problem? Please describe.

Trying to produce messages to Kafka using `aiokafka` from a Temporal Workflow fails [when trying to check if the current event loop is running](https://github.com/aio-libs/aiokafka/blob/master/aiokafka/util.py#L84). This is caused by the the Temporal event loop not fully implement the `AbstractEventLoop` interface, which includes `is_running`. Although more understandable when it comes to thread methods (`to_thread`, etc...), simpler methods like `is_running` should be easy to implement.

### Describe the solution you'd like

Add an `is_running` method to `_WorkflowInstanceImpl` to better conform to the `AbstractEventLoop` interface, perhaps by checking `_deleting`:

```python
def is_running(self) -> bool:
    return not self._deleting
```

Although perhaps it should always be `True` as long as there is a Runtime defined?

### Additional context

The Python doc [states](https://docs.python.org/3.12/library/asyncio-eventloop.html?highlight=abstracteventloop#asyncio.AbstractEventLoop) that custom implementations of `AbstractEventLoop` should have all methods defined [here](https://docs.python.org/3.12/library/asyncio-eventloop.html?highlight=abstracteventloop#asyncio-event-loop-methods). Although they are not being strict about it ("should have defined"), the closer Temporal's event loop gets to the interface, the more it can interoperate with other Python packages, like `aiokafka`.

**Comment by cretz** [comment]
We can't implement all methods of the event loop. You should never call Kafka from inside a workflow, only from inside an activity. A workflow is meant to be deterministic code only. There is never a case where you should need `is_running` and we can't really give an accurate value for that or `is_closed` like a non-distributed event loop can. I guess _technically_ we could just always return `True` from it and always return `False` from `is_closed`, but it's not really accurate as it's never really running/closed in the background like a normal event loop.

**Comment by tomasfarias** [comment]
> You should never call Kafka from inside a workflow, only from inside an activity. A workflow is meant to be deterministic code only.

A call to Kafka (or any other external service) can be made deterministic: It's a matter of handling possible errors in a deterministic fashion. In my case, I ignore them and move on.

> I'm actually kind of glad this raised a not-implemented so it catches illegal things happening to the workflow's event loop, such as code based on whether it's "running" or not as if it was a local event loop.

Not much else to say from my end as this is the direction you are glad to go with. We will deal with the issue from our side. Thank you for taking time to answer this request. I'll go ahead and close it.

**Comment by EdAyers** [comment]
Parts of python standard library assume that is_running and is_closed are implemented:

Eg consider this line in aiohttp https://github.com/aio-libs/aiohttp/blob/3f2f4a705f588d79a8649bfb17018cb30431df89/aiohttp/connector.py#L960
```py
        if sys.version_info >= (3, 12):
            # Optimization for Python 3.12, try to send immediately
            resolved_host_task = asyncio.Task(coro, loop=loop, eager_start=True)
```
And if we look in the stdlib asyncio code we can see this calls:

https://github.com/python/cpython/blob/83827ad81972e8e6438a29274dbdcb923d7b1cc4/Lib/asyncio/tasks.py#L124
```py
        if eager_start and self._loop.is_running():
            self.__eager_start()
```
But is_running() raises a NotImplementedError because you have left the method abstract.

https://github.com/temporalio/sdk-python/blob/0b327b04a95fc7954ed2c9e4e1a6c5de47c51ebd/temporalio/worker/_workflow_instance.py#L195

If you do not support parts of the standard AbstractEventLoop interface that even the standard core python library assumes exists, you need to at the very least reimplement them and give an error message that makes it crystal clear what is being done wrong. This error wasted hours of time trying to figure out what is going wrong (particularly nasty to debug since the event loop is only this special WorkflowInstance thing in certain circumstances).
