### ISSUE TITLE
[Feature Request] Default Workflow\Activity Params In Declaration

### ISSUE THREAD

**Issue by ytaben** [temporalio/sdk-python#588]
### Is your feature request related to a problem? Please describe.
Greetings, this is more of a 'hear your thoughts' kind of feature. If you believe the idea is viable for the SDK - we would also be happy to help with a contribution for it.

As of now - various activity and workflow parameters such as timeouts, task queue, retry policy and so on have to be specified at call sites. What we find in practice from experience - these parameters are _almost_ always tied to the definition\declaration of the workflow\activity itself.

For example - if an author makes a non-idempotent activity that should never be retried - it makes sense to specify maximum attempt to 1 in activity declaration. Same thing with heartbeating: if the author implemented heartbeating - the users will either forget to specify it at call site or copy paste the same heartbeat timeout everywhere. With regular timeouts - we just find people copy-pasting the same values or making helper functions like 'start_my_activity' that encapsulates those params.

### Describe the solution you'd like
The proposed solution is to allow these parameters to be specified in declarations.
For example:
```
@activity.defn(
  task_queue="urgent_important_task_queue",
  start_to_close_timeout=timedelta(minutes=10),
  heartbeat_timeout=timedelta(seconds=30),
  retry_policy=RetryPolicy(maximum_attempts=1)
)
def my_activity(...) -> ...:
  ...
```

In each relevant SDK method - such as `start_activity` or `execute_activity`, etc we would pick call-site value first and fall back to declaration if not given.

### Additional context

The intention would be to keep any existing behavior exactly the same.
There are some edge cases to think about such as having to use a sentinel value as default to allow explicitly setting `None`.

We are also happy to do this in our wrapper internally but wanted to share in case this makes the overall SDK experience better.

**Comment by cretz** [comment]
Many users in all SDKs choose to set their activities at the definition site and often refer to them at call site (or use a helper method for activity invocation that retrieves them). This is very common and we encourage it. It is well known that for many/most, it makes more sense for the activity implementer to define their options than the caller.

However, the SDK is unable to make these general assumptions about which definition site is the actual one desired because the call site may be a completely different set of code (and options) from the definition site. Also, it may give the implementer a false sense of what the options are since the caller is the true definer of the options not the implementer (i.e. can override). The Temporal platform would have to be altered to support worker-side options which we may have in the future but not at this time.

So while we definitely encourage users to put their options where they fit with their code best, I fear at this time without Temporal platform support for declaration-side options, it is too confusing to pretend that it exists (especially since it may exist one day). The lack of this is common across all SDKs and we regularly encourage users to put their reusable options in code where they prefer.

**Comment by ytaben** [comment]
That is fair reasoning.
I, as an end user, would be ok with understanding 'these are defaults but end users override them' but I can see how this extends to situations where it's not even the default. Someone can just call an activity as string from anywhere and the decorator is not at play at all.


I also do think that platform support for worker side options has value (i.e. non-idempotent activities for example) so we'll likely add these default options to our wrapper and if worker side options become a thing - adapt our wrapper then.

Thank you!

**Comment by cretz** [comment]
> I also do think that platform support for worker side options has value

We agree. There is a potential effort coming that will let you update the options externally from the workflow for already starting activities which technically allows activities to update their own options. The more explicit ahead-of-time options definition from a worker will be a bit harder and take longer because Temporal has no mechanism to even make the server aware an activity exists ahead of time much less some options it may have.

**Comment by cretz** [comment]
https://github.com/temporalio/temporal/issues/6339 is a tracking issue for the server-side activity update concept
