### ISSUE TITLE
[Feature Request] Ability to install without having Rust installed 

### ISSUE THREAD

**Issue by crubier** [temporalio/sdk-python#85]
### Is your feature request related to a problem? 

Requiring rust to be installed to pip install this package complicates deployment 

### Describe the solution you'd like

Publish a version that does not require Rust to install with Pip

### Additional context

Trying to use temporal sdk at my company, but we don’t have Rust on our base images. Requiring it complicates things.

**Comment by Geethree** [comment]
Unfortunately, it looks like the core sdk is rust..

https://github.com/temporalio/sdk-python/tree/main/temporalio/bridge

**Comment by cretz** [comment]
@crubier and @Geethree - Our goal is to _not_ require Rust in any way to install. Our last alpha release only had a limited number of wheels pre-built (because it is alpha):

* Windows x64
* macOS x64
* macOS arm64
* Linux x64 for libc >= 2.31

These can be seen at https://pypi.org/project/temporalio/0.1a2/#files. You only need Rust if you aren't on one of those platforms. The next release, coming soon, will support more including Linux x64 for libc >= 2.17 and Linux arm64. If you want to use these wheels now, you can get them as artifacts on the latest successful master build (so https://github.com/temporalio/sdk-python/actions/runs/2712855146 when it's done or https://github.com/temporalio/sdk-python/actions/runs/2712464707 was the last PR).

So after next release, only in rare environments would you ever need Rust.

**Comment by vincent-lecrubier-skydio** [comment]
Cool, indeed, being on ubuntu bionic with libc 2.27, I had to rebuild.

Thank you @cretz !

**Comment by vincent-lecrubier-skydio** [comment]
I was excited to see version 0.1b1 was released, but it does not have a linux aarch64 wheel. 

And for some reason, Trying to install a wheel from github gives me the following error:

```
#0 1.250 ERROR: temporalio-0.1b1-cp37-abi3-manylinux2014_aarch64.manylinux_2_17_aarch64.whl is not a supported wheel on this platform.
```

For reference I am trying to build this:

```dockerfile
# This is a docker image based on Alpine, containing Temporalio only
FROM python:3.10.4-alpine
WORKDIR /app

COPY temporalio-0.1b1-cp37-abi3-manylinux2014_aarch64.manylinux_2_17_aarch64.whl temporalio-0.1b1-cp37-abi3-manylinux2014_aarch64.manylinux_2_17_aarch64.whl

# Install Python pakages, including temporalio
RUN python -m pip install \
  asyncio==3.4.3 \
  /app/temporalio-0.1b1-cp37-abi3-manylinux2014_aarch64.manylinux_2_17_aarch64.whl

# Run everything
COPY . .
CMD ["sh", "-c", "python -m worker.worker"]
```

**Comment by cretz** [comment]
@vincent-lecrubier-skydio - Thanks for testing this for us. I didn't put the wheel in PyPI since we haven't been able to test ourselves.

I have opened #100 specifically about investigating Linux aarch64. We will try to get an environment to test in there. Any help welcome.

In the meantime I am gonna close this general purpose issues since beta has solved this for other environments.
