### ISSUE TITLE
[Feature Request] Lazy connectivity for client and healthCheck

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-python#92]

**Comment by cretz** [comment]
Opened https://github.com/temporalio/sdk-core/issues/367 for health check in Core which this will depend on

**Comment by cretz** [comment]
This depends on https://github.com/temporalio/sdk-core/issues/385

**Comment by cretz** [comment]
There's an open question about how workers are created. In Rust and Python, worker creation is a synchronous task w/ an existing already-connected client. If we make that lazy on the Python side, we have to make worker creation async on the Python side which I think is a bit confusing. Also we can't defer client connection to worker start because we want to eagerly create the worker in Rust so it can do its validation on worker construction.

IMO we need to support lazy connectivity in core. It's not quite right that Rust worker creation gets to be sync but language-level does not.
